group 'com.mapbox.maps.mapbox_maps'
version '1.0.0'

def mapboxDownloadsToken = [
    System.getenv("SDK_REGISTRY_TOKEN"),
    project.findProperty("SDK_REGISTRY_TOKEN"),
    System.getenv("MAPBOX_DOWNLOADS_TOKEN"),
    project.findProperty("MAPBOX_DOWNLOADS_TOKEN"),
].find { value ->
    value != null && value.toString().trim()
}?.toString()

def mapboxSnapshotSdkVersion = '11.24.0-SNAPSHOT-04-23--02-04.git-34e5bee'
def mapboxStableSdkVersion = '11.22.0'
def mapboxAndroidSdkVersion = (
    System.getenv("MAPBOX_ANDROID_SDK_VERSION")
        ?: project.findProperty("MAPBOX_ANDROID_SDK_VERSION")
        ?: (mapboxDownloadsToken != null
            ? mapboxSnapshotSdkVersion
            : mapboxStableSdkVersion)
).toString()

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            if (mapboxDownloadsToken != null) {
                authentication {
                    basic(BasicAuthentication)
                }
                credentials {
                    username = "mapbox"
                    password = mapboxDownloadsToken
                }
            }
        }
        if (mapboxDownloadsToken != null) {
            maven {
                url 'https://api.mapbox.com/downloads/v2/snapshots/maven'
                authentication {
                    basic(BasicAuthentication)
                }
                credentials {
                    username = "mapbox"
                    password = mapboxDownloadsToken
                }
            }
        }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdk 35

    namespace 'com.mapbox.maps.mapbox_maps'
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 21
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

if (file("$rootDir/gradle/ktlint.gradle").exists() && file("$rootDir/gradle/lint.gradle").exists()) {
    project.apply {
        from("$rootDir/gradle/ktlint.gradle")
        from("$rootDir/gradle/lint.gradle")
    }
}

dependencies {
    implementation "com.mapbox.maps:android-ndk27:${mapboxAndroidSdkVersion}"

    implementation "androidx.annotation:annotation:1.5.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
}
